name: 'GitHub Actions Mirror'

on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Arxiv Crawl Daily"]
    branches: [ main ]
    types:
      - completed

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Mirror to gitee
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitee.com:derek_nlp/nlp-arxiv-daily-for-lab.git
          ssh_private_key:
            ${{ secrets.GITEE_KEY }}
